; Generated by ec
; Target: x86_64 Linux (NASM)

%include "coreasm/x86_64/core.asm"
%include "coreasm/x86_64/io.asm"
%include "coreasm/x86_64/file.asm"
%include "coreasm/x86_64/resource.asm"
%include "coreasm/x86_64/heap.asm"
%include "coreasm/x86_64/string.asm"
%include "coreasm/x86_64/args.asm"

section .data
    str_0: db '/dev/stdout', 0
    str_0_len: equ $ - str_0 - 1
    str_1: db '--help', 0
    str_1_len: equ $ - str_1 - 1
    str_2: db 'Usage: cat [OPTION]... [FILE]...', 0
    str_2_len: equ $ - str_2 - 1
    str_3: db 'Concatenate FILE(s) to standard output.', 0
    str_3_len: equ $ - str_3 - 1
    str_4: db 'With no FILE, or when FILE is -, read standard input.', 0
    str_4_len: equ $ - str_4 - 1
    str_5: db '--version', 0
    str_5_len: equ $ - str_5 - 1
    str_6: db 'cat (ec) 0.1.2', 0
    str_6_len: equ $ - str_6 - 1
    str_7: db '/dev/stdin', 0
    str_7_len: equ $ - str_7 - 1
    str_8: db '-', 0
    str_8_len: equ $ - str_8 - 1
    str_9: db '/dev/stdin', 0
    str_9_len: equ $ - str_9 - 1

section .text
global _start

_start:
    ; Save command-line arguments and environment
    SAVE_ARGS

    push rbp
    mov rbp, rsp
    sub rsp, 64

    lea rdi, [str_0]
    FILE_OPEN_WRITE rdi
    mov [rbp-8], rax  ; file descriptor
    test rax, rax
    jns .file_ok_0  ; jump if success (non-negative)
    neg rax  ; convert to positive errno
    mov [rel _last_error], rax
    jmp .file_done_1
.file_ok_0:
    mov qword [rel _last_error], 0  ; clear error
    mov rdi, rax
    call _register_fd  ; track for auto-cleanup
.file_done_1:
    mov rax, 4096
    mov rdi, rax  ; buffer size
    call _alloc_buffer_sized
    mov [rbp-16], rax  ; buffer struct pointer
    lea rax, [str_1]
    mov rbx, rax  ; target argument value
    call _get_argc
    mov rcx, rax  ; argc
    mov r8, 1  ; start at argv[1]
    xor rax, rax  ; default result: false
.arg_has_loop_4:
    cmp r8, rcx
    jge .arg_has_done_6
    mov rdi, r8
    call _get_arg
    mov rdi, rax
    mov rsi, rbx
    call _str_eq
    test rax, rax
    jnz .arg_has_found_5
    inc r8
    jmp .arg_has_loop_4
.arg_has_found_5:
    mov rax, 1
    jmp .arg_has_done_6
.arg_has_done_6:
    test rax, rax
    jz .else_3
    PRINT_STR str_2, str_2_len
    PRINT_NEWLINE
    PRINT_STR str_3, str_3_len
    PRINT_NEWLINE
    PRINT_STR str_4, str_4_len
    PRINT_NEWLINE
    ; exit program
    mov rax, 0
    mov rdi, rax  ; exit code
    push rdi      ; save exit code
    call _cleanup_all
    pop rdi       ; restore exit code
    EXIT rdi
    jmp .if_end_2
.else_3:
.if_end_2:
    lea rax, [str_5]
    mov rbx, rax  ; target argument value
    call _get_argc
    mov rcx, rax  ; argc
    mov r8, 1  ; start at argv[1]
    xor rax, rax  ; default result: false
.arg_has_loop_9:
    cmp r8, rcx
    jge .arg_has_done_11
    mov rdi, r8
    call _get_arg
    mov rdi, rax
    mov rsi, rbx
    call _str_eq
    test rax, rax
    jnz .arg_has_found_10
    inc r8
    jmp .arg_has_loop_9
.arg_has_found_10:
    mov rax, 1
    jmp .arg_has_done_11
.arg_has_done_11:
    test rax, rax
    jz .else_8
    PRINT_STR str_6, str_6_len
    PRINT_NEWLINE
    ; exit program
    mov rax, 0
    mov rdi, rax  ; exit code
    push rdi      ; save exit code
    call _cleanup_all
    pop rdi       ; restore exit code
    EXIT rdi
    jmp .if_end_7
.else_8:
.if_end_7:
    call _get_argc
    cmp rax, 1
    setle al  ; 1 if argc <= 1 (no user args)
    movzx rax, al
    test rax, rax
    jz .else_13
    lea rdi, [str_7]
    FILE_OPEN_READ rdi
    mov [rbp-24], rax  ; file descriptor
    test rax, rax
    jns .file_ok_14  ; jump if success (non-negative)
    neg rax  ; convert to positive errno
    mov [rel _last_error], rax
    jmp .file_done_15
.file_ok_14:
    mov qword [rel _last_error], 0  ; clear error
    mov rdi, rax
    call _register_fd  ; track for auto-cleanup
.file_done_15:
    mov rdi, [rbp-24]
    test rdi, rdi
    js .skip_fd_16  ; skip if invalid fd
    mov rsi, [rbp-16]  ; buffer struct
    mov qword [rsi + 8], 0  ; reset buffer length
    call _read_into_buffer  ; auto-grows if needed
    mov [rbp-16], rsi  ; updated buffer ptr
.skip_fd_16:
.while_start_17:
    mov rax, [rbp-16]
    mov rax, [rax + 8]  ; get size/length
    test rax, rax
    jnz .not_true_19
    jmp .while_end_18
.not_true_19:
    mov rdi, [rbp-8]
    test rdi, rdi
    js .skip_fd_20  ; skip if invalid fd
    mov rsi, [rbp-16]
    FILE_WRITE_BUF rdi, rsi
.skip_fd_20:
    mov rdi, [rbp-24]
    test rdi, rdi
    js .skip_fd_21  ; skip if invalid fd
    mov rsi, [rbp-16]  ; buffer struct
    mov qword [rsi + 8], 0  ; reset buffer length
    call _read_into_buffer  ; auto-grows if needed
    mov [rbp-16], rsi  ; updated buffer ptr
.skip_fd_21:
    jmp .while_start_17
.while_end_18:
    jmp .if_end_12
.else_13:
.if_end_12:
    call _get_argc
    mov [rbp-32], rax  ; argc
    mov qword [rbp-40], 1  ; start at argv[1]
.foreach_start_22:
    mov rax, [rbp-40]  ; index
    cmp rax, [rbp-32]  ; compare with argc
    jge .foreach_end_23
    mov rdi, rax
    call _get_arg
    mov [rbp-48], rax  ; store in filename
    mov rax, [rbp-48]
    push rax  ; save original value
    mov rdi, rax  ; comparison ptr in rdi
    lea rax, [str_8]
    mov rsi, rax  ; match value in rsi
    call _str_eq
    test rax, rax
    jz .treating_skip_24
    add rsp, 8  ; discard saved value
    lea rax, [str_9]
    jmp .treating_done_25
.treating_skip_24:
    pop rax  ; restore original value
.treating_done_25:
    mov rdi, rax  ; path pointer
    FILE_OPEN_READ rdi
    mov [rbp-56], rax  ; file descriptor
    test rax, rax
    jns .file_ok_26  ; jump if success (non-negative)
    neg rax  ; convert to positive errno
    mov [rel _last_error], rax
    jmp .file_done_27
.file_ok_26:
    mov qword [rel _last_error], 0  ; clear error
    mov rdi, rax
    call _register_fd  ; track for auto-cleanup
.file_done_27:
    mov rdi, [rbp-56]
    test rdi, rdi
    js .skip_fd_28  ; skip if invalid fd
    mov rsi, [rbp-16]  ; buffer struct
    mov qword [rsi + 8], 0  ; reset buffer length
    call _read_into_buffer  ; auto-grows if needed
    mov [rbp-16], rsi  ; updated buffer ptr
.skip_fd_28:
.while_start_29:
    mov rax, [rbp-16]
    mov rax, [rax + 8]  ; get size/length
    test rax, rax
    jnz .not_true_31
    jmp .while_end_30
.not_true_31:
    mov rdi, [rbp-8]
    test rdi, rdi
    js .skip_fd_32  ; skip if invalid fd
    mov rsi, [rbp-16]
    FILE_WRITE_BUF rdi, rsi
.skip_fd_32:
    mov rdi, [rbp-56]
    test rdi, rdi
    js .skip_fd_33  ; skip if invalid fd
    mov rsi, [rbp-16]  ; buffer struct
    mov qword [rsi + 8], 0  ; reset buffer length
    call _read_into_buffer  ; auto-grows if needed
    mov [rbp-16], rsi  ; updated buffer ptr
.skip_fd_33:
    jmp .while_start_29
.while_end_30:
    inc qword [rbp-40]
    jmp .foreach_start_22
.foreach_end_23:

    ; Cleanup all resources before exit
    call _cleanup_all

    ; Exit program
    EXIT 0
