; Generated by ec
; Target: x86_64 Linux (NASM)

%include "coreasm/x86_64/core.asm"
%include "coreasm/x86_64/io.asm"
%include "coreasm/x86_64/string.asm"

section .data
    str_0: db 'Hello, World!', 0
    str_0_len: equ $ - str_0 - 1

section .text
global _start

_start:
    push rbp
    mov rbp, rsp

    PRINT_STR str_0, str_0_len
    PRINT_NEWLINE

    ; Exit program
    EXIT 0
